/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_tsinghua_vpn4over6_VPNBackend */

#ifndef _Included_cn_edu_tsinghua_vpn4over6_VPNBackend
#define _Included_cn_edu_tsinghua_vpn4over6_VPNBackend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edu_tsinghua_vpn4over6_VPNBackend
 * Method:    startThread
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_edu_tsinghua_vpn4over6_VPNBackend_startThread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
